### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by MrTAToad** [trenki2/SoftwareRenderer#1]
Hello

I'm having problems with lighting at the moment - with my cube having the same colour on all sides.  I'm using 32-bit RGB graphics.

This is my shade code
vec3x colour = ambient_colour * i.colour;
		for (int i = 0; i < 1; ++i) {
			vec3x ldir = normalize(lights[i].pos - wpos);
			fixed16_t ndotl = max(X(0.0f), dot(wnor, ldir));
			colour += lights[i].colour * ndotl;
		}
		colour *= material_colour;
		for (int i = 0; i < 3; ++i)
			colour[i] = min(X(1.0f), colour[i]);

		out.varyings[0] = colour.x.intValue<<8;
		out.varyings[1] = colour.y.intValue<<8;
		out.varyings[2] = colour.z.intValue<<8;

and this is the single fragment code :

int r = min(max(0, fd.varyings[0] >> 16),255);// >> 2;
		int g = min(max(0, fd.varyings[1] >> 16), 255);// >> 3;
		int b = min(max(0, fd.varyings[2] >> 16), 255);// >> 2;
		SDL_SetRenderDrawColor(m_mainRenderer, r,g,b, SDL_ALPHA_OPAQUE);
		SDL_RenderDrawPoint(m_mainRenderer, x, y);

The only thing I can think of that causes it is the normals, but it does the same with a plane too.

**Comment by trenki2** [comment]
I can't spot a mistake in the code, maybe the problem is the input values like position and normal. Take a look at the cow example, it does lighting, maybe you can adapt it to your needs.

Also, using expensive functions like SDL_SetRenderDrawColor and SDL_RenderDrawPoint in the fragment shader will probably cause a massive slowdown.

**Comment by MrTAToad** [comment]
Silly me - I forgot that, whilst UV coordinates were being set, I wasn't actually calculating the normals properly.

I do need, at some point to get direct access to the SDL2 renderer position (or to a surface - haven't decided which yet), but it would certainly help with the speed (although its not bad at the moment).
