### ISSUE TITLE
Polygon Clipping

### ISSUE THREAD

**Issue by Memnarch** [trenki2/SoftwareRenderer#2]
Hi,
Some years ago i started writing my Softwarerenderer. Recently I got to the point where i needed to implement Polygonclipping.
During the search, in addition to other sources,  i found your article, and this repository.

Before I go any further, in your article (and in the Box-Demo here) i found that your Vertexshader does this:

```
		out->x = position.x;
		out->y = position.y;
		out->z = position.y;
		out->w = position.w;
```
Why do you put Y into Z? Mine does put Z there and that code above seems strange oO

Back to the clipping:
I followed your code (but wrote the algorythm in Delphi), and got this
I have my Triangle:
![grafik](https://user-images.githubusercontent.com/1398184/89076195-1cc26d00-d380-11ea-9dc2-954cd0b7e936.png)
Left edge works (clipping generated new vertices)
![grafik](https://user-images.githubusercontent.com/1398184/89076240-3368c400-d380-11ea-9eb1-8eb49fb62676.png)
Bottom Edge Works
![grafik](https://user-images.githubusercontent.com/1398184/89076273-3ebbef80-d380-11ea-9756-0829afe6e7a1.png)
Right Edge.. well here it starts to clip from the wrong side
![grafik](https://user-images.githubusercontent.com/1398184/89076320-52675600-d380-11ea-86c8-cd2c40f833a9.png)
Same for the upper Edge. (Havent checked near far yet)

I don't think the algorythm needs to be aware, if the system is Z+- or Y+- up oriented?

**Comment by Memnarch** [comment]
Fixed!
Classic Showerthought moment, as it dawned on me while showering. Acessed the vertices using i instead of the Index located in the IndexArray at i XD
(Will rebase later, so commit might be gone)
https://github.com/Memnarch/Mundus/commit/ec8905b49525a5da9b3e3fe4c6aadcb9e9e57402
```diff

diff --git a/Mundus.Renderer.Clipping.pas b/Mundus.Renderer.Clipping.pas
index bac479c..10cf16a 100644
--- a/Mundus.Renderer.Clipping.pas
+++ b/Mundus.Renderer.Clipping.pas
@@ -104,7 +104,7 @@ begin
   for i := 1 to High(AIndices) do
   begin
     LIndex := AIndices[i];
-    LVertex := ACall.Vertices[i];
+    LVertex := ACall.Vertices[LIndex];
     LDotProduct :=  AA * LVertex.X + AB * LVertex.Y + AC  * LVertex.Z + AD * LVertex.W;
 
     if LPrevDotProduct >= 0 then
```

**Comment by Memnarch** [comment]
(EDIT: Okay following is no longer an issue. Seems this was due to precision error when calculating the triangle normal using SSE because i did not do the division by w first anymore, so it seemed to exceed Single(32bit Float) precision.)
Ahh or so i thought. Top/Side faces of a cube are clipped depending on the view angle for some reason. Will look at that tomorrow.
![grafik](https://user-images.githubusercontent.com/1398184/89081156-07067500-d38b-11ea-9bc6-dc372817b1b7.png)
Slightly looking up
![grafik](https://user-images.githubusercontent.com/1398184/89081176-12f23700-d38b-11ea-82b8-8cc630610913.png)

**Comment by trenki2** [comment]
The output coordinate assignement in the box demo had a typo. It should be

```
out->x = position.x;
out->y = position.y;
out->z = position.z;
out->w = position.w;
```

as you pointed out. I corrected and pushed the new code. Somehow it did not have any effect on the output.`

In your last image it seems the backface culling has a problem.

**Comment by Memnarch** [comment]
Yup it's the backface culling. So it actually seems like it's a precision error.
Once the Vertices are projected to the screen, i calculate their surface normal and when fitting, do the polygon clipping.

However, the Surfacenormal-calculation needs XYZ divided by W, but the polygonclipping needs them just the way they were outputet by the vertexshader.

So my current solution is to have a copy of the needed vertices ABC be divided by W, do the normal calculation, and when facing the correct direction execute the Polygonclipping on the VertexBuffer given the indices ABC so it uses the ones which were outputted by the Vertexshader. Once done, i do the perspective division on all vertices in the buffer before passing them to the rasterizer.

SSE doesn't output any floating point errors, but using normal code, i can see NANs popping up, if not done that way -.-

**Comment by trenki2** [comment]
You need to do the polygon clipping against the frustum planes before the perspective divide, viewport transform and culling.
I think only this way you can handle them correctly e.g. in cases where they might intersect the near plane etc.

In my code it is done like this:

```
void VertexProcessor::processPrimitives(DrawMode mode) const
{
	clipPrimitives(mode);
	transformVertices();
	drawPrimitives(mode);
}
```

The triangle culling is in `drawPrimitives()`

**Comment by Memnarch** [comment]
Oh okay, so you check all triangles for clipping and THEN you do the backface culling on the clipped ones? Hoped i could circumvent it.

**Comment by trenki2** [comment]
Yes, clipping is first, then perspective divide and viewport transform and backface culling is last.
